version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruby_app
    command: rails server -b '0.0.0.0'
    volumes:
      - ".:/app"
    expose:
      - "3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8888:80"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

